export const addRoomDefaultFormData = {
    roomType: 'Presidential suite',
    roomName: 'Kempinski Jakarta',
    bedRooms: 1,
    noOfBed: 1,
    roomSize: '2.13 x 3.66 sq.m',
    adults: 2,
    childs: 1,
    BathRooms: 2,
    Balcony: 1,
    pricing: 894,
    allDayPricing: true,
    wifi: true,
    restrurent: true,
    pool: true,
    noSmoking: true,
    parking: true,
    beachView: true,
    balcony: true,
    hotelBar: true,
    commonAreas: true,
    tennisCourts: true,
    airconditioning: true,
    bathtub: true,
    flatScreenTv: true,
    pictures: []
};
